/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package mhp_ph;

import PHControls.PHclose;
import PHControls.PHexport;
import PHControls.PHprinter;
import PHControls.PHresults;
import PHControls.PHtab;
import PHControls.PHtooManyTabs;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Point;
import java.net.URI;
import java.util.LinkedList;
import javax.swing.JDialog;

/**
 *
 * @author artur.szymanski
 */
public class mainForm extends javax.swing.JFrame {

    /** Creates new form mainForm */
    public mainForm() {
        initComponents();
        buildUI();
        this.setLocationRelativeTo(getRootPane());
        this.setSize(800, 600);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHbackground1 = new PHControls.PHbackground();
        pHquickSearch1 = new PHControls.PHquickSearch();
        tab1 = new PHControls.PHresults();
        tabButton1 = new PHControls.PHtab();
        tabButton2 = new PHControls.PHtab();
        tabButton3 = new PHControls.PHtab();
        tabButton4 = new PHControls.PHtab();
        tabButton5 = new PHControls.PHtab();
        pHtextButton1 = new PHControls.PHtextButton();
        pHtextButton2 = new PHControls.PHtextButton();
        pHtextButton3 = new PHControls.PHtextButton();
        pHtextButton4 = new PHControls.PHtextButton();
        tab2 = new PHControls.PHresults();
        tab3 = new PHControls.PHresults();
        tab4 = new PHControls.PHresults();
        tab5 = new PHControls.PHresults();
        tab6 = new PHControls.PHresults();
        tab7 = new PHControls.PHresults();
        tab8 = new PHControls.PHresults();
        pHsearch1 = new PHControls.PHsearch();
        browse = new PHControls.PHyears();
        authors = new PHControls.PHauthors();
        pHtextButton5 = new PHControls.PHtextButton();
        helpTopics = new PHControls.PHhelps();
        tab9 = new PHControls.PHresults();
        helpTopic = new javax.swing.JPanel();
        topic = new javax.swing.JLabel();
        pHbrowse = new PHControls.PHimage();
        pHauthor = new PHControls.PHimage();
        pHclipboard = new PHControls.PHimage();
        pHhelp = new PHControls.PHimage();
        resultsBorder = new PHControls.PHimage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Przegląd Historyczny");
        setFont(new java.awt.Font("Trebuchet MS", 0, 10));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 800, 632));
        setMinimumSize(new java.awt.Dimension(800, 632));
        setModalExclusionType(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pHbackground1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHbackground1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHbackground1MouseExited(evt);
            }
        });
        pHbackground1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pHbackground1MouseMoved(evt);
            }
        });
        pHbackground1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pHquickSearch1.setPreferredSize(new java.awt.Dimension(354, 27));
        pHquickSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHquickSearch1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHquickSearch1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHquickSearch1MouseExited(evt);
            }
        });
        pHquickSearch1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pHquickSearch1FocusGained(evt);
            }
        });
        pHbackground1.add(pHquickSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 24));
        pHbackground1.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 420));

        tabButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabButton1MouseClicked(evt);
            }
        });
        pHbackground1.add(tabButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 82, -1));

        tabButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabButton2MouseClicked(evt);
            }
        });
        pHbackground1.add(tabButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 120, 82, 20));

        tabButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabButton3MouseClicked(evt);
            }
        });
        pHbackground1.add(tabButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 120, 82, 20));

        tabButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabButton4MouseClicked(evt);
            }
        });
        pHbackground1.add(tabButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 120, 82, 20));

        tabButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabButton5MouseClicked(evt);
            }
        });
        pHbackground1.add(tabButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 120, 82, 20));

        pHtextButton1.setText("Zaznacz wszystko");
        pHtextButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton1MouseClicked(evt);
            }
        });
        pHbackground1.add(pHtextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 100, -1));

        pHtextButton2.setText("Do schowka");
        pHtextButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton2MouseClicked(evt);
            }
        });
        pHbackground1.add(pHtextButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 560, 70, -1));

        pHtextButton3.setText("Eksportuj");
        pHtextButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton3MouseClicked(evt);
            }
        });
        pHbackground1.add(pHtextButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 560, 70, -1));

        pHtextButton4.setText("Drukuj");
        pHtextButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton4MouseClicked(evt);
            }
        });
        pHbackground1.add(pHtextButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 560, 62, -1));
        pHbackground1.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 420));
        pHbackground1.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 420));
        pHbackground1.add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 420));
        pHbackground1.add(tab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 420, 420));
        pHbackground1.add(tab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, 420, 438));
        pHbackground1.add(tab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, 420, 438));
        pHbackground1.add(tab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, 420, 438));

        pHsearch1.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        pHbackground1.add(pHsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 330, 470));
        pHbackground1.add(browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        pHbackground1.add(authors, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        pHtextButton5.setPreferredSize(new java.awt.Dimension(90, 24));
        pHtextButton5.setText("Odznacz wszystko");
        pHtextButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton5MouseClicked(evt);
            }
        });
        pHbackground1.add(pHtextButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 560, 100, -1));
        pHbackground1.add(helpTopics, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        pHbackground1.add(tab9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 148, 420, 412));

        helpTopic.setBackground(new java.awt.Color(255, 255, 255));
        helpTopic.setLayout(null);

        topic.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        topic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        topic.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        topic.setPreferredSize(new java.awt.Dimension(400, 18));
        helpTopic.add(topic);
        topic.setBounds(4, 0, 400, 18);

        pHbackground1.add(helpTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, 408, 18));

        pHbrowse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHbrowseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHhelpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pHbrowseLayout = new javax.swing.GroupLayout(pHbrowse);
        pHbrowse.setLayout(pHbrowseLayout);
        pHbrowseLayout.setHorizontalGroup(
            pHbrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        pHbrowseLayout.setVerticalGroup(
            pHbrowseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pHbackground1.add(pHbrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 70, 126, 24));

        pHauthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHauthorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHhelpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pHauthorLayout = new javax.swing.GroupLayout(pHauthor);
        pHauthor.setLayout(pHauthorLayout);
        pHauthorLayout.setHorizontalGroup(
            pHauthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        pHauthorLayout.setVerticalGroup(
            pHauthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pHbackground1.add(pHauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 70, 76, 24));

        pHclipboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHclipboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHhelpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pHclipboardLayout = new javax.swing.GroupLayout(pHclipboard);
        pHclipboard.setLayout(pHclipboardLayout);
        pHclipboardLayout.setHorizontalGroup(
            pHclipboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        pHclipboardLayout.setVerticalGroup(
            pHclipboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pHbackground1.add(pHclipboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 70, 78, 24));

        pHhelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHhelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHhelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHhelpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pHhelpLayout = new javax.swing.GroupLayout(pHhelp);
        pHhelp.setLayout(pHhelpLayout);
        pHhelpLayout.setHorizontalGroup(
            pHhelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        pHhelpLayout.setVerticalGroup(
            pHhelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pHbackground1.add(pHhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 70, 119, 24));

        javax.swing.GroupLayout resultsBorderLayout = new javax.swing.GroupLayout(resultsBorder);
        resultsBorder.setLayout(resultsBorderLayout);
        resultsBorderLayout.setHorizontalGroup(
            resultsBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        resultsBorderLayout.setVerticalGroup(
            resultsBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pHbackground1.add(resultsBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 120, 414, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pHbackground1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pHbackground1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public int currentTab;
    public int tabs;
    public PHresults currentTabRef;
    public PHresults oldTabRef;
    public DLelement db = new DLelement();
    public boolean close = false;

    private void pHquickSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHquickSearch1MouseClicked
        turnQuickOn();
    }//GEN-LAST:event_pHquickSearch1MouseClicked

    private void pHquickSearch1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pHquickSearch1FocusGained
        turnQuickOn();
    }//GEN-LAST:event_pHquickSearch1FocusGained

    private void tabButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabButton1MouseClicked
        hideTabs();
        deactivateTabs();
        tabButton1.activate(true);
        tab1.setVisible(true);
        currentTab = 1;
        currentTabRef = tab1;
    }//GEN-LAST:event_tabButton1MouseClicked

    private void tabButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabButton2MouseClicked
        hideTabs();
        deactivateTabs();
        tabButton2.activate(true);
        tab2.setVisible(true);
        currentTab = 2;
        currentTabRef = tab2;
    }//GEN-LAST:event_tabButton2MouseClicked

    private void tabButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabButton3MouseClicked
        hideTabs();
        deactivateTabs();
        tabButton3.activate(true);
        tab3.setVisible(true);
        currentTab = 3;
        currentTabRef = tab3;
    }//GEN-LAST:event_tabButton3MouseClicked

    private void tabButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabButton4MouseClicked
        hideTabs();
        deactivateTabs();
        tabButton4.activate(true);
        tab4.setVisible(true);
        currentTab = 4;
        currentTabRef = tab4;
    }//GEN-LAST:event_tabButton4MouseClicked

    private void tabButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabButton5MouseClicked
        hideTabs();
        deactivateTabs();
        tabButton5.activate(true);
        tab5.setVisible(true);
        currentTab = 5;
        currentTabRef = tab5;
    }//GEN-LAST:event_tabButton5MouseClicked

    private void pHtextButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton1MouseClicked
        if (currentTabRef != null)
        {
            currentTabRef.selectAll();
        }
    }//GEN-LAST:event_pHtextButton1MouseClicked

    private void pHtextButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton2MouseClicked
        if (currentTabRef != tab8)
        {
            currentTabRef.copy(tab8);
        } else {
            currentTabRef.removeSelected();
        }
    }//GEN-LAST:event_pHtextButton2MouseClicked

    private void pHtextButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton5MouseClicked
        if (currentTabRef != null)
        {
            currentTabRef.deselectAll();
        }
    }//GEN-LAST:event_pHtextButton5MouseClicked

    private void pHbackground1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHbackground1MouseClicked
        Point p = evt.getPoint();
        try
        {
            if (p.x >= 17 && p.y >= 24 && p.x <= 452 && p.y <= 56)
            {
                Desktop.getDesktop().browse(new URI("http://www.dig.com.pl/index.php?s=wyniki&rodz=9&id=15"));
            } else if (p.x >= 525 && p.y >= 22 && p.x <= 679 && p.y <= 51) {
                Desktop.getDesktop().browse(new URI("http://bazhum.muzhp.pl/"));
            } else if (p.x >= 738 && p.y >= 7 && p.x <= 788 && p.y <= 55) {
                Desktop.getDesktop().browse(new URI("http://www.muzhp.pl/"));
            }
        }
        catch (Exception e)
        {
        }
    }//GEN-LAST:event_pHbackground1MouseClicked

    private void pHquickSearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHquickSearch1MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pHquickSearch1MouseEntered

    private void pHquickSearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHquickSearch1MouseExited
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pHquickSearch1MouseExited

    private void pHbackground1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHbackground1MouseMoved
        Point p = evt.getPoint();
        try
        {
            if (p.x >= 17 && p.y >= 24 && p.x <= 452 && p.y <= 56)
            {
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            } else if (p.x >= 525 && p.y >= 22 && p.x <= 679 && p.y <= 51) {
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            } else if (p.x >= 738 && p.y >= 7 && p.x <= 788 && p.y <= 55) {
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            } else {
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
        }
        catch (Exception e)
        {
        }
    }//GEN-LAST:event_pHbackground1MouseMoved

    private void pHbackground1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHbackground1MouseExited
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pHbackground1MouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        PHclose p = new PHclose();
        p.setMainForm(this);
        JDialog d = new JDialog(this, true);
        d.add(p);
        d.setPreferredSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setMinimumSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setMaximumSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setLocationRelativeTo(this);
        d.setResizable(false);
        d.setVisible(true);
        if (close == true)
        {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void pHbrowseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHbrowseMouseClicked
        turnBtnOn();
        pHbrowse.changeImage("przegladaj_on.png");
        hidePanels();
        hideTabs();
        tab6.setVisible(true);
        browse.setVisible(true);
        currentTabRef = tab6;
    }//GEN-LAST:event_pHbrowseMouseClicked

    private void pHauthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHauthorMouseClicked
        turnBtnOn();
        pHauthor.changeImage("autorzy_on.png");
        hidePanels();
        hideTabs();
        tab7.setVisible(true);
        authors.setVisible(true);
        currentTabRef = tab7;
    }//GEN-LAST:event_pHauthorMouseClicked

    private void pHclipboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHclipboardMouseClicked
        turnBtnOn();
        pHclipboard.changeImage("schowek_on.png");
        hidePanels();
        hideTabs();
        pHtextButton2.setText("Usuń");
        tab8.setVisible(true);
        currentTabRef = tab8;
    }//GEN-LAST:event_pHclipboardMouseClicked

    private void pHhelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHhelpMouseClicked
        turnBtnOn();
        pHhelp.changeImage("pomoc_on.png");
        hidePanels();
        hideTabs();
        pHtextButton1.setVisible(false);
        pHtextButton2.setVisible(false);
        pHtextButton3.setVisible(false);
        pHtextButton4.setVisible(false);
        pHtextButton5.setVisible(false);
        helpTopics.setVisible(true);
        helpTopic.setVisible(true);
        tab9.setVisible(true);
    }//GEN-LAST:event_pHhelpMouseClicked

    private void pHhelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHhelpMouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pHhelpMouseEntered

    private void pHhelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHhelpMouseExited
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pHhelpMouseExited

    private void pHtextButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton3MouseClicked
        PHexport p = new PHexport();
        p.setList(currentTabRef.getSelected());
        JDialog d = new JDialog(this, true);
        d.add(p);
        d.setPreferredSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setMinimumSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setMaximumSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setLocationRelativeTo(this);
        d.setResizable(false);
        d.setVisible(true);
    }//GEN-LAST:event_pHtextButton3MouseClicked

    private void pHtextButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton4MouseClicked
        PHprinter p = new PHprinter();
        p.setList(currentTabRef.getSelected());
        JDialog d = new JDialog(this, true);
        d.add(p);
        d.setPreferredSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setMinimumSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setMaximumSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setSize(new Dimension(p.getPreferredSize().width + 8, p.getPreferredSize().height + 32));
        d.setLocationRelativeTo(this);
        d.setResizable(false);
        d.setVisible(true);
    }//GEN-LAST:event_pHtextButton4MouseClicked

    /**
     * Deactivates all tabs
     */
    public void deactivateTabs()
    {
        tabButton1.activate(false);
        tabButton2.activate(false);
        tabButton3.activate(false);
        tabButton4.activate(false);
        tabButton5.activate(false);
    }

    /**
     * Hide all tabs
     */
    public void hideTabs()
    {
        if (currentTabRef == tab1 || currentTabRef == tab2 || currentTabRef == tab3 || currentTabRef == tab4 || currentTabRef == tab5)
        {
            oldTabRef = currentTabRef;
        }
        tab1.setVisible(false);
        tab2.setVisible(false);
        tab3.setVisible(false);
        tab4.setVisible(false);
        tab5.setVisible(false);
        tab6.setVisible(false);
        tab7.setVisible(false);
        tab8.setVisible(false);
        tab9.setVisible(false);
    }

    /**
     * Hide all panels
     */
    private void hidePanels()
    {
        pHsearch1.setVisible(false);
        tabButton1.setVisible(false);
        tabButton2.setVisible(false);
        tabButton3.setVisible(false);
        tabButton4.setVisible(false);
        tabButton5.setVisible(false);
        browse.setVisible(false);
        authors.setVisible(false);
        helpTopics.setVisible(false);
        pHtextButton2.setText("Do schowka");
        pHtextButton1.setVisible(true);
        pHtextButton2.setVisible(true);
        pHtextButton3.setVisible(true);
        pHtextButton4.setVisible(true);
        pHtextButton5.setVisible(true);
        helpTopic.setVisible(false);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    public void buildUI ()
    {
        tabButton1.setText("abc");
        deactivateTabs();
        hideTabs();
        hidePanels();
        currentTab = 1;
        pHsearch1.setMainForm(this);
        tabButton1.setMainForm(this);
        tabButton2.setMainForm(this);
        tabButton3.setMainForm(this);
        tabButton4.setMainForm(this);
        tabButton5.setMainForm(this);
        authors.listLetters(tab7);
        browse.listYears(tab6);
        pHquickSearch1.setMainForm(this);
        helpTopics.showTopics(tab9, helpTopic);
        resultsBorder.changeImage("results_bg.png");
        turnQuickOn();
        replaceImg();
//        pHresults1.add(this)
    /*    PHbackground bg = new PHbackground();
        this.add(bg);
        bg.setBounds(0, 0, 800, 600);
        bg.setLayout(new GroupLayout(bg));

        JPanel searchPane = new JPanel();
        bg.add(searchPane);
        JButton authorButton = new JButton();
        bg.add(authorButton);
        JButton browseButton = new JButton();
        bg.add(browseButton);

        searchPane.setBounds(13, 67, 354, 26);
        searchPane.setBackground(Color.BLACK);
        authorButton.setBounds(499,67, 79, 26);
        authorButton.setIcon(getIc("autorzyOff.jpg", 79, 26));
        browseButton.setBounds(368, 67, 130, 26);
        browseButton.setIcon(getIc("przegladajOff.jpg", 130, 26));
*/
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PHControls.PHauthors authors;
    private PHControls.PHyears browse;
    private javax.swing.JPanel helpTopic;
    private PHControls.PHhelps helpTopics;
    private PHControls.PHimage pHauthor;
    private PHControls.PHbackground pHbackground1;
    private PHControls.PHimage pHbrowse;
    private PHControls.PHimage pHclipboard;
    private PHControls.PHimage pHhelp;
    private PHControls.PHquickSearch pHquickSearch1;
    private PHControls.PHsearch pHsearch1;
    private PHControls.PHtextButton pHtextButton1;
    private PHControls.PHtextButton pHtextButton2;
    private PHControls.PHtextButton pHtextButton3;
    private PHControls.PHtextButton pHtextButton4;
    private PHControls.PHtextButton pHtextButton5;
    private PHControls.PHimage resultsBorder;
    public PHControls.PHresults tab1;
    public PHControls.PHresults tab2;
    public PHControls.PHresults tab3;
    public PHControls.PHresults tab4;
    public PHControls.PHresults tab5;
    private PHControls.PHresults tab6;
    private PHControls.PHresults tab7;
    private PHControls.PHresults tab8;
    private PHControls.PHresults tab9;
    public PHControls.PHtab tabButton1;
    public PHControls.PHtab tabButton2;
    public PHControls.PHtab tabButton3;
    public PHControls.PHtab tabButton4;
    public PHControls.PHtab tabButton5;
    private javax.swing.JLabel topic;
    // End of variables declaration//GEN-END:variables

    protected void turnBtnOn ()
    {
        replaceImg();
        pHquickSearch1.setBackground(Color.black);
        pHquickSearch1.changeState(false);
    }

    public void turnQuickOn ()
    {
        hidePanels();
        hideTabs();
        deactivateTabs();
        pHsearch1.setVisible(true);
        pHsearch1.revalidate();
        pHsearch1.repaint();
        if (tabs > 0)
        {
            tabButton1.setVisible(true);
            tabButton1.revalidate();
            tabButton1.repaint();
        }
        if (tabs > 1)
        {
            tabButton2.setVisible(true);
        }
        if (tabs > 2)
        {
            tabButton3.setVisible(true);
        }
        if (tabs > 3)
        {
            tabButton4.setVisible(true);
        }
        if (tabs > 4)
        {
            tabButton5.setVisible(true);
        }
        if (tabs > 0 && oldTabRef != null)
        {
            oldTabRef.setVisible(true);
            oldTabRef.revalidate();
            oldTabRef.repaint();
        }
        if (currentTab == 1)
        {
            tabButton1.activate(true);
            currentTabRef = tab1;
        } else if (currentTab == 2) {
            tabButton2.activate(true);
            currentTabRef = tab2;
        } else if (currentTab == 3) {
            tabButton3.activate(true);
            currentTabRef = tab3;
        } else if (currentTab == 4) {
            tabButton4.activate(true);
            currentTabRef = tab4;
        } else if (currentTab == 5) {
            tabButton5.activate(true);
            currentTabRef = tab5;
        }
        replaceImg();
        float[] RGBConv = Color.RGBtoHSB(94, 88, 88, null);
        pHquickSearch1.setBackground(Color.getHSBColor(RGBConv[0], RGBConv[1], RGBConv[2]));
        pHquickSearch1.changeState(true);
    }

    public void replaceImg ()
    {
        pHbrowse.changeImage("przegladaj_off.png");
        pHauthor.changeImage("autorzy_off.png");
        pHclipboard.changeImage("schowek_off.png");
        pHhelp.changeImage("pomoc_off.png");
/*        if (pHBrowse1 == b1)
            pHBrowse1.imgName = pHBrowse1.imgName.replaceAll("Off", "On");
        else
            pHBrowse1.imgName = pHBrowse1.imgName.replaceAll("On", "Off");
        if (pHauthor1 == b1)
            pHauthor1.imgName = pHauthor1.imgName.replaceAll("Off", "On");
        else
            pHauthor1.imgName = pHauthor1.imgName.replaceAll("On", "Off");
        if (pHclipboard1 == b1)
            pHclipboard1.imgName = pHclipboard1.imgName.replaceAll("Off", "On");
        else
            pHclipboard1.imgName = pHclipboard1.imgName.replaceAll("On", "Off");
        if (pHhelp1 == b1)
            pHhelp1.imgName = pHhelp1.imgName.replaceAll("Off", "On");
        else
            pHhelp1.imgName = pHhelp1.imgName.replaceAll("On", "Off");

        pHBrowse1.repaint();
        pHauthor1.repaint();
        pHclipboard1.repaint();
        pHhelp1.repaint(); */
    }

    public void quickSearch(String text)
    {
        if (tabs == 5)
        {
            PHtooManyTabs p = new PHtooManyTabs();
            p.setVisible(true);
            return;
        }
        turnQuickOn();
        PHresults tab = null;
        PHtab button = null;
        switch (++tabs)
        {
            case 1:
            {
                tab = tab1;
                button = tabButton1;
                currentTab = 1;
                currentTabRef = tab1;
                break;
            }
            case 2:
            {
                tab = tab2;
                button = tabButton2;
                currentTab = 2;
                currentTabRef = tab2;
                break;
            }
            case 3:
            {
                tab = tab3;
                button = tabButton3;
                currentTab = 3;
                currentTabRef = tab3;
                break;
            }
            case 4:
            {
                tab = tab4;
                button = tabButton4;
                currentTab = 4;
                currentTabRef = tab4;
                break;
            }
            case 5:
            {
                tab = tab5;
                button = tabButton5;
                currentTab = 5;
                currentTabRef = tab5;
                break;
            }
        }
        button.setText(text);
        button.setVisible(true);
        deactivateTabs();
        hideTabs();
        tab.setVisible(true);
        button.activate(true);
        try
        {
            tab.getPanel().removeAll();
            LinkedList<phArt> ll = new LinkedList<phArt>();
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            ll = db.generalSearch(text);
            for (phArt e : ll )
            {
                tab.addArt(e);
            }
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            tab.repaint();
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
}
