/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 * Authors panel
 * @author paulx
 */
public class PHauthors extends javax.swing.JPanel {

    /** Creates new form PHauthors */
    public PHauthors() {
        initComponents();
        pHresults1.pHscroll1.getScroll().setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        JPanel j = new JPanel();
        j.setPreferredSize(new Dimension(250, 1));
        j.setBackground(new Color(255, 255, 255));
        pHresults1.getPanel().add(j);
        pHresults1.getPanel().setBorder(new EmptyBorder(0, 4, 0, 0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pHresults1 = new PHControls.PHresults();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        pHresults1.setBackground(new java.awt.Color(255, 255, 255));
        pHresults1.setMinimumSize(new java.awt.Dimension(262, 470));
        pHresults1.setPreferredSize(new java.awt.Dimension(262, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pHresults1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addComponent(pHresults1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private PHControls.PHresults pHresults1;
    // End of variables declaration//GEN-END:variables

    /**
     * List all letters except X
     * @param tab Result tab
     */
    public void listLetters(PHresults tab)
    {
        for (char i = 'A'; i <= 'Z'; i++)
        {
            if (i != 'X')
            {
                PHtextLink p = new PHtextLink();
                p.setText(String.valueOf(i));
                p.setType(PHtextLink.types.nameList);
                p.setOutputTab(pHresults1, tab);
                p.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
                p.setForeground(new java.awt.Color(88, 88, 88));
                p.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.add(p);
            }
        }
    }
}
