/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

import javax.swing.JDialog;
import mhp_ph.mainForm;

/**
 * Close dialog
 * @author paulx
 */
public class PHclose extends javax.swing.JPanel {

    /** Creates new form PHclose */
    public PHclose() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pHtextButton1 = new PHControls.PHtextButton();
        pHtextButton2 = new PHControls.PHtextButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(260, 80));
        setPreferredSize(new java.awt.Dimension(260, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Czy chcesz zamknąć aplikację?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 10, -1, -1));

        pHtextButton1.setText("Tak");
        pHtextButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton1MouseClicked(evt);
            }
        });
        add(pHtextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        pHtextButton2.setText("Nie");
        pHtextButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton2MouseClicked(evt);
            }
        });
        add(pHtextButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void pHtextButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton1MouseClicked
        main.close = true;
        ((JDialog)getParent().getParent().getParent().getParent()).dispose();
    }//GEN-LAST:event_pHtextButton1MouseClicked

    private void pHtextButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton2MouseClicked
        main.close = false;
        ((JDialog)getParent().getParent().getParent().getParent()).dispose();
    }//GEN-LAST:event_pHtextButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private PHControls.PHtextButton pHtextButton1;
    private PHControls.PHtextButton pHtextButton2;
    // End of variables declaration//GEN-END:variables

    private mainForm main; ///< Main form to close

    /**
     * Sets main form to close
     * @param form Main form
     */
    public void setMainForm(mainForm form)
    {
        main = form;
    }
}
