/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

import java.awt.Desktop;
import java.awt.Dimension;
import java.net.URI;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.border.EmptyBorder;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 * Help panel
 * @author paulx
 */
public class PHhelps extends javax.swing.JPanel {

    /** Creates new form PHhelps */
    public PHhelps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topics = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        topics.setBackground(new java.awt.Color(255, 255, 255));
        topics.setPreferredSize(new java.awt.Dimension(300, 350));
        topics.setLayout(new javax.swing.BoxLayout(topics, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(topics, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topics, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel topics;
    // End of variables declaration//GEN-END:variables

    /**
     * Show topics
     * @param tab Result panel
     * @param tab2 Title panel
     */
    public void showTopics(PHresults tab, JPanel tab2)
    {
        PHtextLink p = addTopic("Informacje ogólne", tab, tab2, "1", "0", "1");
        addTopic("        Program", tab, tab2, "2", "1", "1");
        addTopic("        Licencja", tab, tab2, "3", "1", "1");
        addTopic("        Kontakt", tab, tab2, "4", "1", "1");
        addTopic("        Czasopismo", tab, tab2, "5", "1", "1");
        addTopic("        Bazhum", tab, tab2, "6", "1", "1");
        addTopic("Ekran Szukaj", tab, tab2, "7", "0", "2");
        addTopic("        Menu górne", tab, tab2, "8", "2", "2");
        addTopic("        Wyszukiwanie proste i zaawansowane", tab, tab2, "9", "2", "2");
        addTopic("        Panel lewy", tab, tab2, "10", "2", "2");
        addTopic("        Konstruowanie kwerend", tab, tab2, "11", "2", "2");
        addTopic("        Panel prawy", tab, tab2, "12", "2", "2");
        addTopic("        Zakładki", tab, tab2, "13", "2", "2");
        addTopic("        Menu dolne", tab, tab2, "14", "2", "2");
        addTopic("Ekran Przeglądaj", tab, tab2, "15", "0", "0");
        addTopic("Ekran Autorzy", tab, tab2, "16", "0", "0");
        addTopic("Ekran Schowek", tab, tab2, "17", "0", "0");
        JTextPane t = new JTextPane();
        t.setPreferredSize(new Dimension(tab.getPreferredSize().width - 32, tab.getPreferredSize().height));
        t.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        t.setForeground(new java.awt.Color(88, 88, 88));
        t.setBackground(new java.awt.Color(255, 255, 255));
        t.setDisabledTextColor(new java.awt.Color(88, 88, 88));
        t.setEditable(false);
        t.setEnabled(false);
        t.setBorder(new EmptyBorder(4, 4, 4, 4));
        t.setContentType("text/html");
        t.addHyperlinkListener(new HyperlinkListener() {

            @Override
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    try
                    {
                        Desktop.getDesktop().browse(new URI(e.getDescription()));
                    }
                    catch (Exception ex)
                    {
                    }
                }
            }
        });
        tab.getPanel().add(t);
        p.helpTopic();
    }

    /**
     * Add topic to help left panel
     * @param topic Topic
     * @param tab Result panel
     * @param tab2 Title panel
     * @param n Number as String
     * @param v Number as String
     * @param w Number as String
     * @return Generated PHtextLink
     */
    private PHtextLink addTopic(String topic, PHresults tab, JPanel tab2, String n, String v, String w)
    {
        PHtextLink p = new PHtextLink();
        p.setPanel(tab2);
        p.setOutputTab(tab, null);
        p.setData(v, w, n);
        p.setType(PHtextLink.types.helpTopic);
        p.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
        p.setForeground(new java.awt.Color(88, 88, 88));
        p.setBackground(new java.awt.Color(255, 255, 255));
        p.setText(topic);
        p.setParentPanel(topics);
        p.setMaximumSize(new Dimension(p.getMaximumSize().width, 32));
        topics.add(p);
/*        JLabel l = new JLabel();
        l.setFont(new java.awt.Font("Trebuchet MS", 0, 10));
        l.setText(" ");
        topics.add(l); */
        return p;
    }
}
