/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

import java.util.LinkedList;
import javax.swing.JDialog;
import mhp_ph.PHprint;
import mhp_ph.PHprint.format;
import mhp_ph.phArt;

/**
 * Print dialog
 * @author paulx
 */
public class PHprinter extends javax.swing.JPanel {

    /** Creates new form PHprinter */
    public PHprinter() {
        initComponents();
        formatBN.setIcon(PHsingleIcon.getIcon());
        formatKH.setIcon(PHsingleIcon.getIcon());
        formatPH.setIcon(PHsingleIcon.getIcon());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        formatPH = new javax.swing.JRadioButton();
        formatKH = new javax.swing.JRadioButton();
        formatBN = new javax.swing.JRadioButton();
        ok = new PHControls.PHtextButton();
        cancel = new PHControls.PHtextButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(260, 190));
        setMinimumSize(new java.awt.Dimension(260, 190));
        setPreferredSize(new java.awt.Dimension(260, 190));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Wybierz sposób zapisu bibliograficznego:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        formatPH.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(formatPH);
        formatPH.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        formatPH.setForeground(new java.awt.Color(64, 64, 64));
        formatPH.setSelected(true);
        formatPH.setText("wg Przeglądu Historycznego");
        add(formatPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        formatKH.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(formatKH);
        formatKH.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        formatKH.setForeground(new java.awt.Color(64, 64, 64));
        formatKH.setText("wg Kwartalnika Historycznego");
        add(formatKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        formatBN.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(formatBN);
        formatBN.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        formatBN.setForeground(new java.awt.Color(64, 64, 64));
        formatBN.setText("wg Biblioteki Narodowej");
        add(formatBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        ok.setText("OK");
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 24));

        cancel.setText("Anuluj");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 24));
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        PHprint.format f = format.ph;
        if (formatPH.isSelected())
        {
            f = format.ph;
        } else if (formatKH.isSelected()) {
            f = format.kh;
        } else if (formatBN.isSelected()) {
            f = format.bn;
        }
        if (PHprint.print(ll, f))
        {
            ((JDialog)getParent().getParent().getParent().getParent()).dispose();
        }
}//GEN-LAST:event_okMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        ((JDialog)getParent().getParent().getParent().getParent()).dispose();
}//GEN-LAST:event_cancelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private PHControls.PHtextButton cancel;
    private javax.swing.JRadioButton formatBN;
    private javax.swing.JRadioButton formatKH;
    private javax.swing.JRadioButton formatPH;
    private javax.swing.JLabel jLabel1;
    private PHControls.PHtextButton ok;
    // End of variables declaration//GEN-END:variables

    private LinkedList<phArt> ll; ///< List with articles to print

    /**
     * Sets articles to print
     * @param l List with articles
     */
    public void setList(LinkedList<phArt> l)
    {
        ll = l;
    }
    
}
