/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

import java.awt.Color;

/**
 * Text tab
 * @author paulx
 */
public class PHtext extends javax.swing.JPanel {

    /** Creates new form PHtext */
    public PHtext() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(64, 24));

        jLabel1.setBackground(new java.awt.Color(222, 222, 222));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 188, 188));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public boolean active = false; ///< Active state

    /**
     * Sets text
     * @param text New text
     */
    public void setText(String text)
    {
        jLabel1.setText(text);
    }

    /**
     * Gets text
     * @return Text
     */
    public String getText()
    {
        return jLabel1.getText();
    }

    /**
     * Activate or deactivate
     * @param state Activate state
     */
    public void activate(boolean state)
    {
        active = state;
        refresh();
    }

    /**
     * Refresh panel
     */
    private void refresh()
    {
        if (active) {
            jLabel1.setBackground(new Color(88, 88, 88));
            jLabel1.setForeground(new Color(255, 255, 255));
            this.setBackground(new Color(88, 88, 88));
        } else {
            jLabel1.setBackground(new Color(222, 222, 222));
            jLabel1.setForeground(new Color(188, 188, 188));
            this.setBackground(new Color(222, 222, 222));
        }
    }
}
