/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

/**
 * Too many tabs dialog
 * @author paulx
 */
public class PHtooManyTabs extends javax.swing.JFrame {

    /** Creates new form PHtooManyTabs */
    public PHtooManyTabs() {
        initComponents();
        setLocationRelativeTo(getParent());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        pHtextButton1 = new PHControls.PHtextButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Żeby utworzyć kolejną zakładkę, zamknij jedną z otwartych.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jTextArea1.setMargin(new java.awt.Insets(4, 4, 4, 4));
        jTextArea1.setPreferredSize(new java.awt.Dimension(140, 48));
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 55));

        pHtextButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        pHtextButton1.setMinimumSize(new java.awt.Dimension(0, 24));
        pHtextButton1.setPreferredSize(new java.awt.Dimension(80, 24));
        pHtextButton1.setText("OK");
        pHtextButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHtextButton1MouseClicked(evt);
            }
        });
        getContentPane().add(pHtextButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pHtextButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHtextButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_pHtextButton1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PHtooManyTabs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private PHControls.PHtextButton pHtextButton1;
    // End of variables declaration//GEN-END:variables

}
