/**
 * Copyright 2010 Muzeum Historii Polski w Warszawie
 *
 * This file is part of PH100.
 *
 * PH100 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * PH100 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with PH100. If not, see <http://www.gnu.org/licenses/>.
 */


package PHControls;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import mhp_ph.DLelement;

/**
 * Years panel
 * @author paulx
 */
public class PHyears extends javax.swing.JPanel {

    /** Creates new form PHyears */
    public PHyears() {
        initComponents();
        pHresults1.pHscroll1.getScroll().setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
//        pHresults1.getPanel().setBorder(new EmptyBorder(0, 4, 0, 0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pHresults1 = new PHControls.PHresults();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(48, 470));
        jPanel1.setLayout(null);

        pHresults1.setAlignmentX(0.0F);
        pHresults1.setAlignmentY(0.0F);
        pHresults1.setPreferredSize(new java.awt.Dimension(262, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHresults1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pHresults1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private PHControls.PHresults pHresults1;
    // End of variables declaration//GEN-END:variables

    /**
     * List years, volumes and numbers
     * @param tab
     */
    public void listYears(PHresults tab)
    {
        jPanel1.removeAll();
        pHresults1.getPanel().removeAll();
        int n = 0;
        for (int i = 1905; i < 2009; i += 10)
        {
            PHtextLink p = new PHtextLink();
            p.setText(String.valueOf(i));
            p.setType(PHtextLink.types.dateList);
            p.setOutputTab(pHresults1, tab);
            p.setData(String.valueOf(i), null, null);
            p.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
            p.setForeground(new java.awt.Color(88, 88, 88));
            p.setBackground(new java.awt.Color(255, 255, 255));
            p.setBounds(0, (int)(n++ * 45.5), 44, 20);
            jPanel1.add(p);
        }
        LinkedList<ArrayList<String>> ll = DLelement.getYearsList();
        String last = "";
        JPanel j = null;
        JPanel j2 = null;
        JLabel jl = null;
        PHtextLink pOld = null;
        for (ArrayList<String> l : ll)
        {
            if (l.get(1).compareTo(last) != 0)
            {
                if (last.compareTo("") != 0)
                {
                    j.setPreferredSize(new Dimension(250, j.getPreferredSize().height));
                    pHresults1.getPanel().add(j);
                }
                last = new String(l.get(1));
                j = new JPanel(new BorderLayout());
                j2 = new JPanel();
                j.setBackground(new Color(255, 255, 255));
                j2.setBackground(new Color(255, 255, 255));
                PHtextLink p = new PHtextLink();
                p.setText(l.get(1));
                p.setType(PHtextLink.types.dateVolumeResults);
                p.setData(l.get(0), l.get(1), l.get(2));
                p.setOutputTab(tab, null);
                p.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                p.setForeground(new java.awt.Color(88, 88, 88));
                p.setBackground(new java.awt.Color(255, 255, 255));
                p.setPanel(null);
                j2.add(p);
                jl = new JLabel();
                jl.setText("   ");
                jl.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                jl.setForeground(new java.awt.Color(88, 88, 88));
                jl.setBackground(new java.awt.Color(255, 255, 255));
                j2.add(jl);
                pOld = p;
                p = new PHtextLink();
                p.setText(l.get(0));
                p.setType(PHtextLink.types.dateResults);
                p.setData(l.get(0), l.get(1), l.get(2));
                p.setOutputTab(tab, null);
                p.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                p.setForeground(new java.awt.Color(166, 166, 166));
                p.setBackground(new java.awt.Color(255, 255, 255));
                p.setPanel(null);
                j2.add(p);
                j.add(j2, BorderLayout.WEST);
                if (l.get(2).compareTo("") != 0) {
                    pHresults1.getPanel().add(j);
                    j = new JPanel(new BorderLayout());
                    j2 = new JPanel();
                    pOld.setPanel(j);
                    p.setPanel(j);
                    j.setAlignmentX((float)1.0);
                    j.setVisible(false);
                    j.setBackground(new Color(255, 255, 255));
                    j2.setBackground(new Color(255, 255, 255));
                    jl = new JLabel();
                    jl.setText(" ");
                    jl.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                    jl.setForeground(new java.awt.Color(88, 88, 88));
                    jl.setBackground(new java.awt.Color(255, 255, 255));
                    j2.add(jl);
                    p = new PHtextLink();
                    p.setText(l.get(2));
                    p.setType(PHtextLink.types.dateVolumeNumberResults);
                    p.setData(l.get(0), l.get(1), l.get(2));
                    p.setOutputTab(tab, null);
                    p.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                    p.setForeground(new java.awt.Color(88, 88, 88));
                    p.setBackground(new java.awt.Color(255, 255, 255));
                    j2.add(p);
                    j.add(j2, BorderLayout.WEST);
                }
            } else {
                jl = new JLabel();
                jl.setText("  |  ");
                jl.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                jl.setForeground(new java.awt.Color(88, 88, 88));
                jl.setBackground(new java.awt.Color(255, 255, 255));
                j2.add(jl);
                PHtextLink p = new PHtextLink();
                p.setText(l.get(2));
                p.setType(PHtextLink.types.dateVolumeNumberResults);
                p.setData(l.get(0), l.get(1), l.get(2));
                p.setOutputTab(tab, null);
                p.setFont(new java.awt.Font("Trebuchet MS", 0, 11));
                p.setForeground(new java.awt.Color(88, 88, 88));
                p.setBackground(new java.awt.Color(255, 255, 255));
                j2.add(p);
            }
        }
        j.setPreferredSize(new Dimension(250, j.getPreferredSize().height));
        pHresults1.getPanel().add(j);
    }
}
